# Generated by Django 2.1 on 2018-09-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20180925_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=500),
        ),
    ]
