# Generated by Django 2.1 on 2018-10-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_auto_20181013_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
